# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.StatusCode'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='short_name',
            field=models.CharField(choices=[('BOOKED', 'Order Booked'), ('DELIVER', 'Order Delivered'), ('CANCELLED', 'Order Cancelled')], default='BOOKED', max_length=10),
        ),
    ]
