# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20160331_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='all_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_shop',
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
