# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='shop_area',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='shops',
            name='shop_pincode',
            field=models.IntegerField(default=110001),
        ),
    ]
