# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160317_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='qty_type',
            field=models.CharField(choices=[('PL', '/ plate'), ('WT', '/ 1000g')], default='PL', max_length=2),
        ),
    ]
