# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_qty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qty_type',
            field=models.CharField(choices=[('/plate', '/ plate'), ('/1000g', '/ 1000g')], default='/plate', max_length=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('SWEET', 'sweet'), ('SNACK', 'snack')], max_length=5),
        ),
    ]
